name: Plex Web Interface Monitor

on:
  schedule:
    # Run at random minutes each hour between 8:00-23:00 and 0:00-2:00
    - cron: '37 8-23,0-2 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-plex:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3
        
    - name: Run Plex Web check
      env:
        PLEX_URL: ${{ secrets.PLEX_URL }}
        PLEX_DISCORD_WEBHOOK: ${{ secrets.PLEX_DISCORD_WEBHOOK }}
        START_HOUR: ${{ secrets.START_HOUR }}
        END_HOUR: ${{ secrets.END_HOUR }}
      run: python plex_monitor.py
