name: Plex Cloudflare Bypass Monitor
on:
  schedule:
    # Run at random minutes each hour between 8:00-23:00 and 0:00-2:00
    - cron: '17 8-23,0-2 * * *'
  workflow_dispatch:  # Allows manual triggering
jobs:
  check-plex:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright requests
        
    - name: Install Playwright with dependencies
      run: |
        playwright install-deps chromium
        playwright install chromium
        
    - name: Configure Playwright for CI
      run: |
        # Create a directory for storing cookies between runs
        mkdir -p ~/.playwright-data
        # Restore cookies if they exist
        if [ -f ".playwright-cookies/cloudflare_cookies.json" ]; then
          mkdir -p ~/.playwright-data
          cp .playwright-cookies/cloudflare_cookies.json ~/.playwright-data/
        fi
        
    - name: Run Plex Browser check with Xvfb
      env:
        PLEX_URL: ${{ secrets.PLEX_URL }}
        PLEX_USERNAME: ${{ secrets.PLEX_USERNAME }}
        PLEX_PASSWORD: ${{ secrets.PLEX_PASSWORD }}
        PLEX_DISCORD_WEBHOOK: ${{ secrets.PLEX_DISCORD_WEBHOOK }}
        START_HOUR: ${{ secrets.START_HOUR }}
        END_HOUR: ${{ secrets.END_HOUR }}
        # Use display for non-headless mode
        DISPLAY: ":99"
      run: |
        # Start Xvfb
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        # Run the monitor
        python plex_playwright_monitor.py.py
        
    - name: Save cookies for future runs
      if: always()  # Run this step even if previous steps fail
      run: |
        mkdir -p .playwright-cookies
        if [ -f "cloudflare_cookies.json" ]; then
          cp cloudflare_cookies.json .playwright-cookies/
        fi
        
    - name: Upload screenshots
      if: always()  # Run this step even if previous steps fail
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: |
          plex_page.png
          cloudflare_challenge.png
          after_cloudflare.png
